# Force-pushes master from HEAD (main) to keep it in sync as legacy default branch
name: Sync Master
on: workflow_call

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - run: git push --force origin HEAD:refs/heads/master
