# Truncate pushed tags and force-push as vN major version branch (necessary for workflow_call)
# This workflow assumes the latest tag is the "highest" for its vMajor
name: Tag Major Version

on:
  push: { tags: "v*.*.*" }
  workflow_call:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - env:
          tag: ${{github.ref}}
        run: |
          tag=${tag#refs/tags/}
          major=${tag%%.*}
          git push -f origin "HEAD:refs/heads/$major"
