name: Test
on:
  workflow_call:

jobs:
  npm-cit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with: { cache: npm }
      - run: npm cit
        env:
          BATS_LIB_PATH: ${{ github.workspace }}/node_modules
