name: Test
on:
  workflow_call:

jobs:
  npm-cit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm cit
        env:
          BATS_LIB_PATH: ${{ github.workspace }}/node_modules
