name: Test
on:
  workflow_call:
    inputs:
      npm:
        description: "Run npm-test job."
        default: true
        required: false
        type: boolean

permissions: { contents: read }
jobs:
  npm-test:
    if: inputs.npm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: { os: [ubuntu-latest, macOS-latest] }
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with: { egress-policy: audit }
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: npm cit
        env:
          BATS_LIB_PATH: ${{ github.workspace }}/node_modules

  npm-test-bash-versions:
    if: inputs.npm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        version: [3, 4, 5, rc]
    container:
      image: bash:${{ matrix.version }}
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with: { egress-policy: audit }
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: apk add --update npm
      - run: npm cit
        env:
          BATS_LIB_PATH: ${{ github.workspace }}/node_modules

  dependency-review:
    if: startsWith('pull_request', github.event_name)
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with: { egress-policy: audit }
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1

  ossf-scorecard:
    if: github.ref_name == github.event.repository.default_branch
    permissions: { id-token: write, security-events: write }
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with: { egress-policy: audit }
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde # v2.4.2
        with:
          results_file: ossf-scorecard-results.sarif
          results_format: sarif
          publish_results: true
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ossf-scorecard-results.sarif
          path: ossf-scorecard-results.sarif
      - uses: github/codeql-action/upload-sarif@d6bbdef45e766d081b84a2def353b0055f728d3e # v3.29.3
        with:
          sarif_file: ossf-scorecard-results.sarif
