name: Test
on:
  workflow_call:
    inputs:
      npm:
        description: "Run npm-test job."
        default: true
        required: false
        type: boolean

jobs:
  npm-test:
    if: inputs.npm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: { os: [ubuntu-latest, macOS-latest] }

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: npm cit
        env:
          BATS_LIB_PATH: ${{ github.workspace }}/node_modules
